/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Sarita
 */
public class PanelDeColores extends javax.swing.JPanel {
 public Color colorSeleccionado = Color.black;
    /**
     * Creates new form PanelDeColores
     */
    public PanelDeColores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        negro = new javax.swing.JLabel();
        blanco = new javax.swing.JLabel();
        gris = new javax.swing.JLabel();
        grisClaro = new javax.swing.JLabel();
        granate = new javax.swing.JLabel();
        rojo = new javax.swing.JLabel();
        verdeCaqui = new javax.swing.JLabel();
        amarillo = new javax.swing.JLabel();
        verdeOscuro = new javax.swing.JLabel();
        verdeClaro = new javax.swing.JLabel();
        mostaza = new javax.swing.JLabel();
        azulClarito = new javax.swing.JLabel();
        azulOscuro = new javax.swing.JLabel();
        azul = new javax.swing.JLabel();
        morado = new javax.swing.JLabel();
        rosa = new javax.swing.JLabel();
        verdeOscurito = new javax.swing.JLabel();
        amarilloClaro = new javax.swing.JLabel();
        verdeSuperOscuro = new javax.swing.JLabel();
        verdeSuperClarito = new javax.swing.JLabel();
        azulSuperClarito = new javax.swing.JLabel();
        verdeAgua = new javax.swing.JLabel();
        purpura = new javax.swing.JLabel();
        moradoOscuro = new javax.swing.JLabel();
        azulAgua = new javax.swing.JLabel();
        rosita = new javax.swing.JLabel();
        marron = new javax.swing.JLabel();
        naranja = new javax.swing.JLabel();
        SaberColor = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        negro.setBackground(new java.awt.Color(0, 0, 0));
        negro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        negro.setOpaque(true);
        negro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                negroMousePressed(evt);
            }
        });

        blanco.setBackground(new java.awt.Color(255, 255, 255));
        blanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        blanco.setOpaque(true);
        blanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                blancoMousePressed(evt);
            }
        });

        gris.setBackground(new java.awt.Color(153, 153, 153));
        gris.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gris.setOpaque(true);
        gris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                grisMousePressed(evt);
            }
        });

        grisClaro.setBackground(new java.awt.Color(204, 204, 204));
        grisClaro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        grisClaro.setOpaque(true);
        grisClaro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                grisClaroMousePressed(evt);
            }
        });

        granate.setBackground(new java.awt.Color(153, 0, 0));
        granate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        granate.setOpaque(true);
        granate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                granateMousePressed(evt);
            }
        });

        rojo.setBackground(new java.awt.Color(255, 0, 51));
        rojo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rojo.setOpaque(true);
        rojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rojoMousePressed(evt);
            }
        });

        verdeCaqui.setBackground(new java.awt.Color(153, 153, 0));
        verdeCaqui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verdeCaqui.setOpaque(true);
        verdeCaqui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verdeCaquiMousePressed(evt);
            }
        });

        amarillo.setBackground(new java.awt.Color(255, 255, 0));
        amarillo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        amarillo.setOpaque(true);
        amarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                amarilloMousePressed(evt);
            }
        });

        verdeOscuro.setBackground(new java.awt.Color(0, 153, 0));
        verdeOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verdeOscuro.setOpaque(true);
        verdeOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verdeOscuroMousePressed(evt);
            }
        });

        verdeClaro.setBackground(new java.awt.Color(51, 255, 0));
        verdeClaro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verdeClaro.setOpaque(true);
        verdeClaro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verdeClaroMousePressed(evt);
            }
        });

        mostaza.setBackground(new java.awt.Color(204, 204, 0));
        mostaza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mostaza.setOpaque(true);
        mostaza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mostazaMousePressed(evt);
            }
        });

        azulClarito.setBackground(new java.awt.Color(51, 255, 255));
        azulClarito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        azulClarito.setOpaque(true);
        azulClarito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                azulClaritoMousePressed(evt);
            }
        });

        azulOscuro.setBackground(new java.awt.Color(0, 51, 153));
        azulOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        azulOscuro.setOpaque(true);
        azulOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                azulOscuroMousePressed(evt);
            }
        });

        azul.setBackground(new java.awt.Color(0, 51, 255));
        azul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        azul.setOpaque(true);
        azul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                azulMousePressed(evt);
            }
        });

        morado.setBackground(new java.awt.Color(153, 0, 153));
        morado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        morado.setOpaque(true);
        morado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moradoMousePressed(evt);
            }
        });

        rosa.setBackground(new java.awt.Color(255, 51, 255));
        rosa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rosa.setOpaque(true);
        rosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rosaMousePressed(evt);
            }
        });

        verdeOscurito.setBackground(new java.awt.Color(102, 102, 0));
        verdeOscurito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verdeOscurito.setOpaque(true);
        verdeOscurito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verdeOscuritoMousePressed(evt);
            }
        });

        amarilloClaro.setBackground(new java.awt.Color(255, 255, 102));
        amarilloClaro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        amarilloClaro.setOpaque(true);
        amarilloClaro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                amarilloClaroMousePressed(evt);
            }
        });

        verdeSuperOscuro.setBackground(new java.awt.Color(0, 102, 51));
        verdeSuperOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verdeSuperOscuro.setOpaque(true);
        verdeSuperOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verdeSuperOscuroMousePressed(evt);
            }
        });

        verdeSuperClarito.setBackground(new java.awt.Color(102, 255, 102));
        verdeSuperClarito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verdeSuperClarito.setOpaque(true);
        verdeSuperClarito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verdeSuperClaritoMousePressed(evt);
            }
        });

        azulSuperClarito.setBackground(new java.awt.Color(0, 204, 204));
        azulSuperClarito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        azulSuperClarito.setOpaque(true);
        azulSuperClarito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                azulSuperClaritoMousePressed(evt);
            }
        });

        verdeAgua.setBackground(new java.awt.Color(0, 153, 153));
        verdeAgua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        verdeAgua.setOpaque(true);
        verdeAgua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verdeAguaMousePressed(evt);
            }
        });

        purpura.setBackground(new java.awt.Color(204, 153, 255));
        purpura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        purpura.setOpaque(true);
        purpura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                purpuraMousePressed(evt);
            }
        });

        moradoOscuro.setBackground(new java.awt.Color(153, 51, 255));
        moradoOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        moradoOscuro.setOpaque(true);
        moradoOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moradoOscuroMousePressed(evt);
            }
        });

        azulAgua.setBackground(new java.awt.Color(0, 153, 255));
        azulAgua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        azulAgua.setOpaque(true);
        azulAgua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                azulAguaMousePressed(evt);
            }
        });

        rosita.setBackground(new java.awt.Color(255, 153, 255));
        rosita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rosita.setOpaque(true);
        rosita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rositaMousePressed(evt);
            }
        });

        marron.setBackground(new java.awt.Color(153, 0, 0));
        marron.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        marron.setOpaque(true);
        marron.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                marronMousePressed(evt);
            }
        });

        naranja.setBackground(new java.awt.Color(255, 102, 0));
        naranja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        naranja.setOpaque(true);
        naranja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                naranjaMousePressed(evt);
            }
        });

        SaberColor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        SaberColor.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(blanco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(negro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(grisClaro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gris, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(granate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verdeCaqui, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verdeClaro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verdeOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(azulClarito, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostaza, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(azul, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(azulOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rosa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(morado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(amarilloClaro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verdeOscurito, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verdeSuperClarito, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verdeSuperOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verdeAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(azulSuperClarito, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moradoOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purpura, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rosita, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(azulAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(naranja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marron, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SaberColor, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaberColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(marron, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(naranja, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(azulAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rosita, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(purpura, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(moradoOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(azulSuperClarito, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(verdeAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(verdeSuperOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(verdeSuperClarito, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(verdeOscurito, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(amarilloClaro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(morado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rosa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(azulOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(azul, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mostaza, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(azulClarito, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(verdeOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(verdeClaro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(verdeCaqui, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(granate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(gris, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(grisClaro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(negro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(blanco, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void negroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negroMousePressed
        colorSeleccionado = Color.black;
        SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_negroMousePressed

    private void blancoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blancoMousePressed
       colorSeleccionado = Color.white;
       SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_blancoMousePressed

    private void grisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grisMousePressed
      JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_grisMousePressed

    private void grisClaroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grisClaroMousePressed
      JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_grisClaroMousePressed

    private void granateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_granateMousePressed
       JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_granateMousePressed

    private void rojoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rojoMousePressed
       JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_rojoMousePressed

    private void verdeCaquiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeCaquiMousePressed
       JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_verdeCaquiMousePressed

    private void amarilloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amarilloMousePressed
        JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_amarilloMousePressed

    private void verdeOscuroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeOscuroMousePressed
        JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_verdeOscuroMousePressed

    private void verdeClaroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeClaroMousePressed
       JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_verdeClaroMousePressed

    private void mostazaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostazaMousePressed
       JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_mostazaMousePressed

    private void azulClaritoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_azulClaritoMousePressed
        JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_azulClaritoMousePressed

    private void azulOscuroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_azulOscuroMousePressed
       JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_azulOscuroMousePressed

    private void azulMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_azulMousePressed
        JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_azulMousePressed

    private void moradoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moradoMousePressed
       JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_moradoMousePressed

    private void rosaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rosaMousePressed
      JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_rosaMousePressed

    private void verdeOscuritoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeOscuritoMousePressed
       JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_verdeOscuritoMousePressed

    private void amarilloClaroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amarilloClaroMousePressed
      JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_amarilloClaroMousePressed

    private void verdeSuperOscuroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeSuperOscuroMousePressed
      JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_verdeSuperOscuroMousePressed

    private void verdeSuperClaritoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeSuperClaritoMousePressed
       JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_verdeSuperClaritoMousePressed

    private void azulSuperClaritoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_azulSuperClaritoMousePressed
        JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_azulSuperClaritoMousePressed

    private void verdeAguaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeAguaMousePressed
        JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_verdeAguaMousePressed

    private void purpuraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purpuraMousePressed
       JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_purpuraMousePressed

    private void moradoOscuroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moradoOscuroMousePressed
       JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_moradoOscuroMousePressed

    private void azulAguaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_azulAguaMousePressed
       JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_azulAguaMousePressed

    private void rositaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rositaMousePressed
       JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_rositaMousePressed

    private void marronMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marronMousePressed
        JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_marronMousePressed

    private void naranjaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naranjaMousePressed
        JLabel s = (JLabel) evt.getSource();
      colorSeleccionado = s.getBackground();
      SaberColor.setBackground(colorSeleccionado);
    }//GEN-LAST:event_naranjaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SaberColor;
    private javax.swing.JLabel amarillo;
    private javax.swing.JLabel amarilloClaro;
    private javax.swing.JLabel azul;
    private javax.swing.JLabel azulAgua;
    private javax.swing.JLabel azulClarito;
    private javax.swing.JLabel azulOscuro;
    private javax.swing.JLabel azulSuperClarito;
    private javax.swing.JLabel blanco;
    private javax.swing.JLabel granate;
    private javax.swing.JLabel gris;
    private javax.swing.JLabel grisClaro;
    private javax.swing.JLabel marron;
    private javax.swing.JLabel morado;
    private javax.swing.JLabel moradoOscuro;
    private javax.swing.JLabel mostaza;
    private javax.swing.JLabel naranja;
    private javax.swing.JLabel negro;
    private javax.swing.JLabel purpura;
    private javax.swing.JLabel rojo;
    private javax.swing.JLabel rosa;
    private javax.swing.JLabel rosita;
    private javax.swing.JLabel verdeAgua;
    private javax.swing.JLabel verdeCaqui;
    private javax.swing.JLabel verdeClaro;
    private javax.swing.JLabel verdeOscurito;
    private javax.swing.JLabel verdeOscuro;
    private javax.swing.JLabel verdeSuperClarito;
    private javax.swing.JLabel verdeSuperOscuro;
    // End of variables declaration//GEN-END:variables
}
